services:
  postgres:
    image: postgres:16-alpine
    container_name: circulari_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: circulari
      POSTGRES_PASSWORD: circulari
      POSTGRES_DB: circulari_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: circulari_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
